# Generated by Django 3.2 on 2021-05-12 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_alter_task_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitionfile',
            name='submition_parent',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Submition',
        ),
        migrations.DeleteModel(
            name='SubmitionFile',
        ),
        migrations.DeleteModel(
            name='TaskItem',
        ),
    ]
