# Generated by Django 3.2 on 2021-04-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_submition_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='task',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker.task'),
        ),
    ]
