# Generated by Django 3.2 on 2021-05-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_alter_departmentfile_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentfile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker.department'),
        ),
    ]
